### ISSUE TITLE
Job change hotbars not working with 6.1 update

### ISSUE THREAD

**Issue by helixhamin** [Fr4nsson/FFXIV-Config#1]
Hello. It seems update 6.1 broke your hotbars for job change.

**Comment by easyngit** [comment]
> 

You can fix them yourself by changing jobs in the macros from for example "RDM" to "Red Mage"

**Comment by Fr4nsson** [comment]
Update will be out soon. You can join the [beta](https://discord.gg/7TJG9H8Xyf) if you want.
